image: maven:3-jdk-8

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - build
  - test

mavenbuild:
  stage: build
  script: "mvn clean install -B"

junit:
  stage: test
  script: "mvn test"
